baseurl = "https://not-lpc.github.io/notlpc-concept/"
canonifyurls = true
# Pointing to this file
config = "config.toml"
enableGitInfo = true
paginate=  100
copyright = ""
defaultContentLanguage = "en"
languageCode = "en-gb"

# Set to true to keep url path preserve casing (eg, for sections)
disablePathToLower = false

# Enable Logging
log = true
# Log Filepath (if set, logging enabled automatically)
logFile = ""
# This accepts yaml, toml, or json
metaDataFormat = "yaml"
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles = false
relativeURLs = false
# Display memory and timing of different steps of the program
stepAnalysis = true


# This is the top-level, global site title
title = "North of Tyne LPC"


# Change this once you've created your theme
theme = "notlpc-theme"

# Set to true to convert mysite/section/ to mysite/section.html
uglyURLs = false
verbose = true
verboseLog = false
# Setting this to false will keep hugo from watching for changes during local development
watch = true



[social]
twitter = "NOTLPC"

#CUSTOM PARAMS
[params]
  description = "North of Tyne Local Pharmaceutical Committee"
  ## Used for views in rendered HTML (i.e., rather than using the .Hugo variable)
  release = "0.20"
  ## Setting this to true will add a "noindex" to *EVERY* page on the site
  removefromexternalsearch = false
  ## This is used when the BaseURL does not need to modified (eg, in share links or in prerender, prefetch, etc to control for relativeURLs setting); do *not* include trailing slash
  siteaddress = "https://northoftyneplc.com"

  ## Google Tag Manager
  gtmid = ""

  flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"

  #sidebar_direction = "sidebar_left"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true


## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  tag = "tags"
  category = "categories"


# High level items
[[menu.docs]]
  name = "Local Services"
  weight = 15
  identifier = "local-services"
  post = ""
  url = "/local-services/"
[[menu.docs]]
  name = "Advanced Services"
  weight = 40
  identifier = "advanced-services"
  post = ""
  url = "/advanced-services/"
[[menu.docs]]
  name = "Pharmacy Funding"
  weight = 50
  identifier = "pharmacy-funding"
  post = "break"
  url = "/pharmacy-funding/"
[[menu.docs]]
  name = "Training & Support"
  weight = 90
  post = "break"
  identifier = "training"
  url = "/training/"
[[menu.docs]]
  name = "About North of Tyne LPC"
  weight = 100
  post= "spacer"
  identifier = "about"
  url = "/about/"

######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO siteaddress

[[menu.global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"
[[menu.global]]
  name = "Events"
  weight = 10
  identifier = "events"
  url = "/events/"
[[menu.global]]
  name = "Resources"
  weight = 20
  identifier = "resources"
  url = "/resources/"
[[menu.global]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about/"
# Anything with a weight > 100 gets an external icon
[[menu.global]]
  name = "PSNC"
  weight = 200
  identifier = "psnc"
  post = "external"
  url = "https://psnc.org.uk/lpcs/"
