baseurl = "https://www.northoftynelpc.com/"
canonifyurls = true
# Pointing to this file
config = "config.toml"
enableGitInfo = true
paginate=  100
copyright = ""
defaultContentLanguage = "en"
languageCode = "en-gb"

# Set to true to keep url path preserve casing (eg, for sections)
disablePathToLower = false

# Enable Logging
log = true
# Log Filepath (if set, logging enabled automatically)
logFile = ""
# This accepts yaml, toml, or json
metaDataFormat = "yaml"
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles = false
relativeURLs = false
# Display memory and timing of different steps of the program
stepAnalysis = true


# This is the top-level, global site title
title = "North of Tyne LPC"


# Change this once you've created your theme
theme = "notlpc-theme"

# Set to true to convert mysite/section/ to mysite/section.html
uglyURLs = false
verbose = true
verboseLog = false
# Setting this to false will keep hugo from watching for changes during local development
watch = true

# SectionPagesMenu = "docs"



#CUSTOM PARAMS
[params]
  description = "North of Tyne Local Pharmaceutical Committee"
  descriptionnews = "LPC News and Announcements"
  descriptionevents = "Upcoming Events"
  descriptionfooter = "North of Tyne LPC is recognised, under section 167 of the NHS Act 2006, as the statutory body representing the community pharmacies in Northumberland, Newcastle and North Tyneside"
  ## Used for views in rendered HTML (i.e., rather than using the .Hugo variable)
  release = "0.20"
  ## Setting this to true will add a "noindex" to *EVERY* page on the site
  removefromexternalsearch = false
  ## This is used when the BaseURL does not need to modified (eg, in share links or in prerender, prefetch, etc to control for relativeURLs setting); do *not* include trailing slash
  siteaddress = "https://www.northoftyneplc.com"

  ## Google Tag Manager
  gtmid = ""


  flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"

  #sidebar_direction = "sidebar_left"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true


## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  tag = "tags"
  category = "categories"

[params.social]
  twitter = "NoT_LPC"
  facebook = "NoTLPC"

## Contact Email
[params.contact]
  title = "Contact Us"
  email = "lpc@northoftynelpc.com"

# 'error' defines error messages for invalid inputs
[params.contact.form.name]
  text = "Name"
  error = "Please enter your name."

[params.contact.form.email]
  text = "Email Address"
  error = "Please enter your email address."

[params.contact.form.phone]
  text = "Phone Number"
  error = "Please enter your phone number."

[params.contact.form.message]
  text = "Message"
  error = "Please enter a message."

[params.contact.form.button]
  text = "Send"

[params.contacts]
  [params.contacts.DefaultContact]
    #Required for each!
    name  = "North Of Tyne LPC"
    email = "lpc@northoftynelpc.com"
    phone = "07976132006"
    #Optional
    linkedin = ""
    twitter = "NoT_LPC"
    facebook= "NoTLPC"
  [params.contacts.StephenBlackman]
    #Required for each!
    name  = "Stephen Blackman"
    email = "stephen.blackman@northoftynelpc.com"
    phone = "07976132006"
    #Optional
    linkedin = "sablackman"
    twitter = "NoT_LPC_CO"
    facebook= "NoTLPC"
  [params.contacts.AnnGunning]
    #Required for each!
    name  = "Ann Gunning"
    email = "ann.gunning@northoftynelpc.com"
    phone = "07832967622"
    #Optional
    linkedin = "ann-gunning-15713829"
    twitter = "NoT_LPC"
    facebook= "NoTLPC"     

# High level items
[[menu.docs]]
  name = "Local Services"
  weight = 10
  identifier = "local-services"
  post = ""
  url = "/local-services/"
[[menu.docs]]
  name = "Essential Services"
  weight = 20
  identifier = "essential-services"
  post = ""
  url = "/essential-services/"
[[menu.docs]]
  name = "Advanced Services"
  weight = 30
  identifier = "advanced-services"
  post = "break"
  url = "/advanced-services/"
[[menu.docs]]
  name = "Pharmacy Contract & IT"
  weight = 40
  identifier = "pharmacy-contract"
  post = "break"
  url = "/pharmacy-contract/"
[[menu.docs]]
  name = "Dispensing & Supply"
  weight = 50
  post = "break"
  identifier = "dispensing"
  url = "/dispensing/"
[[menu.docs]]
  name = "Training & Support"
  weight = 60
  identifier = "training"
  post = ""
  url = "/training/"
[[menu.docs]]
  name = "Other Resources"
  weight = 70
  post = "break"
  identifier = "other-resources"
  url = "/other-resources/"
# [[menu.docs]]
#   name = "About Us"
#   weight = 100
#   post= "spacer"
#   identifier = "about"
#   url = "/about/"

######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO siteaddress

[[menu.global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"
[[menu.global]]
  name = "Events"
  weight = 10
  identifier = "events"
  url = "/events/"
[[menu.global]]
  name = "Resources"
  weight = 20
  identifier = "resources"
  url = "/resources/"
[[menu.global]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.global]]
  name = "Contact"
  weight = 40
  identifier = "contact"
  url = "/contact/"
# Anything with a weight > 100 gets an external icon
[[menu.global]]
  name = "PSNC"
  weight = 200
  identifier = "psnc"
  post = "external"
  url = "https://psnc.org.uk/"
